### ISSUE TITLE
Footsteps not working

### ISSUE THREAD

**Issue by PizzaStuk** [Sollace/Presence-Footsteps#217] opened 2023-05-19 14:42 UTC
For some reason i just dont hear footsteps at all. Im playing on 1.19.4 feather and i used to hear footsteps when i first installed the mod but now they just dissapeared. Anyone knows a fix for this?

**Comment by Sollace** [comment] 2023-05-19 20:54
Duplicate of #216

**Closed by Sollace** 2023-05-19 20:54 UTC
