### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by notIkibo** [Sollace/Presence-Footsteps#296] opened 2024-03-29 17:09 UTC
Generated a new singleplayer world. After Terrain Generation MC crashed
Just wanted to be a somewhat good citizen and show it here. Modpack is full of clientside mods.

newest 1.20.4 version of presence footsteps

[crash-2024-03-29_18.03.22-client.txt](https://github.com/Sollace/Presence-Footsteps/files/14806831/crash-2024-03-29_18.03.22-client.txt)

Lovely mod. 💋
Keep it up

**Comment by Andre601** [comment] 2024-03-30 15:04
Encounter a crash too when joining a server.
It loads a resource pack from the server and once that completes, the client simply crashes.

Seems to be an issue with PF trying to use a class or alike (loco) that is null.

My full client logs from starting to joining the server:
https://mclo.gs/AZPHxWe

**Comment by Andre601** [comment] 2024-03-30 15:06
And to further add to this: Using the previous version (1.11.1) makes the crash go away, but also results in no sounds being played while walking.

**Comment by Sollace** [comment] 2024-03-30 23:57
Delete your config file.

Duplicate of #282

**Closed by Sollace** 2024-03-30 23:57 UTC
