### ISSUE TITLE
Mud squishes sound on boat/raft

### ISSUE THREAD

**Issue by MaoYan5985** [Sollace/Presence-Footsteps#233] opened 2023-09-08 13:03 UTC
![S9CV7GU`V2E {8T QJCJ5L9](https://github.com/Sollace/Presence-Footsteps/assets/122714639/f0cd3066-4c66-414c-be7b-41b2b921c97c)
As shown in the screenshot, jumping or walking on the boat/raft will make mud squishes sound, which is obvious incorrect. Maybe splashing sound is more appropriate.

MC : 1.20.1
Fabric : fabric-loader-0.14.22
Mod ver : PresenceFootsteps-1.9.0

**Comment by Sollace** [comment] 2023-09-27 22:42
Duplicate of #232 (caused by the same thing)

**Closed by Sollace** 2023-09-27 22:42 UTC
