### ISSUE TITLE
Crash in Deathduskmodpack

### ISSUE THREAD

**Issue by TheButterbrotMan** [Sollace/Presence-Footsteps#144] opened 2022-05-25 10:22 UTC
What happened?
Found a End City, entered it and my game crashed now when i try to log in again it always crash...welp

Provide the log
https://bytebin.lucko.me/bhQrUuiQGR

**Comment by macmawhiney** [comment] 2022-05-27 17:38
I have the same problem...

**Comment by Sollace** [comment] 2022-05-30 12:30
Ah, so sorry! I had worked on this but forgot to push it.

**Comment by Sollace** [comment] 2022-05-30 12:33
Duplicate of #135

**Closed by Sollace** 2022-05-30 12:33 UTC
Labels: bug, confirmed for next release

**Comment by TheButterbrotMan** [comment] 2022-06-25 20:09
When you will push the new version?

**Comment by TheButterbrotMan** [comment] 2022-06-25 20:10
@Sollace When you will push the new version?

**Comment by Sollace** [comment] 2022-06-27 13:23
@TheButterbrotMan The fix has already been released. Update to 1.19.
