### ISSUE TITLE
Ancient City Immersion Problem

### ISSUE THREAD

**Issue by Theov0re** [Sollace/Presence-Footsteps#222] opened 2023-07-06 16:41 UTC
So, when going in the Ancient City with the mod, you'll find something interesting. Sneaking around will not emit any sound, but things like jumping and going down stairs and slabs still emit sound despite them not releasing any vibrations, which does break the immersion of sneaking around the Ancient City somewhat. Interestingly enough, this also applies to jumping and then falling at least a half block, which is very immersion-breaking in my opinion since there is no silent way to descend any distance despite not releasing any vibrations.

I think a very easy solution would be to just remove those sounds while you are sneaking. That way, the immersion of having to be _very_ careful would be kept. A bonus would be that sneaking in general would also be improved, whether it's in the Ancient City or near an unsuspecting player :)

**Comment by Sollace** [comment] 2023-08-05 19:53
Duplicate of #226

**Closed** 2023-08-05 19:53 UTC
