### ISSUE TITLE
No way to disable certain sounds for certain blocks

### ISSUE THREAD

**Issue by Ketsuna009** [Sollace/Presence-Footsteps#113] opened 2021-12-09 18:15 UTC
There's no options in the config to disable certain sounds on certain blocks. On the nylium blocks it sounds like you're walking through a puddle rather than a soft mat of mycelium or moss. I find the sound really disturbing and difficult to deal with when I'm in the nether because its constant rather than occasional (like when its raining), and it doesn't really match what makes sense in my head (cause mycelium isn't like so saturated with water that it splashes).

**Comment by Sollace** [comment] 2021-12-09 20:07
You can customise all of the sounds with a resourcepack. If you don't like how they sound, you can change them.

**Comment by Sollace** [comment] 2021-12-09 20:09
Duplicate of #107

**Closed by Sollace** 2021-12-09 20:09 UTC
