### ISSUE TITLE
Request: Apugli Mod (Origins Addon)

### ISSUE THREAD

**Issue by EpicDark76** [Sollace/Presence-Footsteps#223] opened 2023-07-19 21:52 UTC
Hi there,
the origins addon mod [Apugli](https://www.curseforge.com/minecraft/mc-mods/apugli) adds a certain power type: "[Custom Footstep](https://apugli.readthedocs.io/en/latest/types/power_types/custom_footstep/)". That power type let's you change the sound of the entities footsteps, as well as completly mute them.
When the footsteps are muted, in normal minecraft you can't hear them, however with the presence footsteps mod you definitely can.
Is it possible to somehow integrate that, so that even players with the pf. mod can't hear footsteps when they are muted by Apugli?
Thanks

**Comment by Sollace** [comment] 2023-09-06 14:22
That depends on how Apugli is muting them. It might be something I can fix, but I'm not sure.

**Comment by Sollace** [comment] 2024-03-26 22:53
Closing as this is likely a duplicate of #138

**Closed by Sollace** 2024-03-26 22:53 UTC
Labels: enhancement, compatibility
