### ISSUE TITLE
Crash while loading a world

### ISSUE THREAD

**Issue by bafb** [Sollace/Presence-Footsteps#290] opened 2024-03-17 23:44 UTC
The game crashed whilst generating pf sounds for entity
Error: java.lang.NullPointerException: Cannot invoke "eu.ha3.presencefootsteps.sound.generator.Locomotion.supplyGenerator(net.minecraft.class_1309, eu.ha3.presencefootsteps.sound.SoundEngine)" because "loco" is null

[crash-2024-03-17_17.38.42-client.txt](https://github.com/Sollace/Presence-Footsteps/files/14629316/crash-2024-03-17_17.38.42-client.txt)

**Comment by Sollace** [comment] 2024-03-18 22:11
Duplicate of https://github.com/Sollace/Presence-Footsteps/issues/282

**Closed by Sollace** 2024-03-18 22:11 UTC
