### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by samve000** [Sollace/Presence-Footsteps#328] opened 2024-07-18 22:07 UTC
The client log keeps spamming: 
[Render thread/WARN] (soundcontroller) Unable to find volume for sound presencefootsteps:...

I'm also experiencing some tps lag so maybe it's because of that...

**Comment by NovaLynxie** [comment] 2024-08-20 09:15
I too have been seeing log spam like this, though for sound groups instead and have no idea how to disable it from clogging up my console logs. It looks like this except for each block type that exists in the game or whichever I would have defined.
```
[10:09:38] [Render thread/INFO]: Getting sound group for block.minecraft.sandstone
[10:09:38] [Server thread/INFO]: Getting sound group for block.minecraft.sandstone
```
It is incredibly annoying and has seemingly started up out of nowhere, its worse especially when a lot of mobs start making footstep noises. Please tell us there is a way to disable this, as this generates wasteful amounts of data for repetitive lines in log files.

**Comment by NovaLynxie** [comment] 2024-11-02 10:48
Unfortunately, it seems I may have since removed the setups with the log files containing these errors, so I cannot remember which version I have been using since it was from 2 months prior as I have done some cleanup of my main storage.
The only versions I remember using were 1.20.1 or 1.21 around that time, unsure if I can reproduce it. Sorry, I can't be of more help here.

**Comment by Sollace** [comment] 2024-11-02 17:58
It's very likely the logs don't exist in the current version then. I suppose I'll close this, and if I happen to see them in the 1.20.1 branch I'll note their removal in the changelog.

**Closed by Sollace** 2024-11-02 17:58 UTC
Labels: bug
