### ISSUE TITLE
Crash on world load. 1.20.1 Fabric

### ISSUE THREAD

**Issue by szunakabeats** [Sollace/Presence-Footsteps#291] opened 2024-03-18 07:15 UTC
modlist in the crashlog

presence footsteps 1.9.2
Fabric loader 0.15.7
fabric-api 0.92.0+1.20.1

[crash-2024-03-18_08.11.39-client.txt](https://github.com/Sollace/Presence-Footsteps/files/14632270/crash-2024-03-18_08.11.39-client.txt)

**Comment by Sollace** [comment] 2024-03-18 22:10
Delete your config and restart the game. This has already been fixed and will be part of the next release.

**Comment by Sollace** [comment] 2024-03-18 22:11
Duplicate of https://github.com/Sollace/Presence-Footsteps/issues/282

**Closed by Sollace** 2024-03-18 22:11 UTC
