### ISSUE TITLE
Request: Is it possible to have the equipment sound when the player walks?

### ISSUE THREAD

**Issue by akki96144** [Sollace/Presence-Footsteps#280] opened 2024-03-05 18:58 UTC
A mod called Dynamic Surroundings makes equipment sounds when the player walks. Could this feature be added to Presence Footsteps as well?

Or is there any way to make the sounds of Dynamic Surroundings equipment audible when this mod is installed...

**Comment by Sollace** [comment] 2024-03-06 19:45
Duplicate of @228

**Comment by Sollace** [comment] 2024-03-06 19:46
Duplicate of #228

**Closed** 2024-03-06 19:46 UTC
