### ISSUE TITLE
You can hear footsteps of another player, no matter how far they are

### ISSUE THREAD

**Issue by SilverHatTrick** [Sollace/Presence-Footsteps#93] opened 2021-05-26 14:29 UTC
You can hear the footsteps from other players, no matter how far they are. I'm assuming this is a client-side issue, and I have no idea how to fix this. This problem also occurs with the rest of my playerbase, and as a server owner, I'm trying my best as to how I can find a solution. Here's a latest log from my server: https://pastebin.com/UE6AaGVS

This is my modpack that we are using: https://www.curseforge.com/minecraft/modpacks/rise-and-fall-kingdoms/relations/dependencies

~ ~ ~

Please, let me know what I can do to fix it on our end, or if this is something that needs to be resolved by you guys/another mod developer. Thank you very much!

**Comment by Sollace** [comment] 2021-05-26 17:00
The sounds are played on the client and are [attenuated by distance](https://github.com/Sollace/Presence-Footsteps/blob/9cdd0002042bdc433254973e9e0b2b9f10298b88/src/main/java/eu/ha3/presencefootsteps/sound/player/ImmediateSoundPlayer.java#L65) (I remember testing that locally and it worked just fine). 

Can you try on a client without any other mods to see whether any of them are causing this?

**Comment by SilverHatTrick** [comment] 2021-05-26 18:47
> The sounds are played on the client and are [attenuated by distance](https://github.com/Sollace/Presence-Footsteps/blob/9cdd0002042bdc433254973e9e0b2b9f10298b88/src/main/java/eu/ha3/presencefootsteps/sound/player/ImmediateSoundPlayer.java#L65) (I remember testing that locally and it worked just fine).
> 
> Can you try on a client without any other mods to see whether any of them are causing this?

The only problem is, this occurs with other players, so I'd need another server in order to test this. I am thinking that it is a mod incompatibility with either Charmonium, Dynamic Music, MAmbience or Music Duration Reducer, since they all affect sound in one way? Less likely candidates are Gibly's Voice Chat, and Audio output.

**Comment by Sollace** [comment] 2021-05-26 19:41
It very well could be one of those.

As for singleplayer options, you can either:
1. change Entities to "All" in the settings the spawn some pigs and listen to them
2. start a lan server or join Hypixel and listen to other player's footprints there

**Comment by Sollace** [comment] 2021-05-26 19:42
I did test this recently in my dev environment was able to confirm no issue there, so it is most likely one of your other mods causing a conflict.

**Comment by Sollace** [comment] 2021-06-09 08:50
Closing as this is now for a previous version of the mod, and I couldn't reproduce it anway. Feel free to report again if you find the issue is still happening in r30 (1.17)

**Closed by Sollace** 2021-06-09 08:50 UTC
Labels: bug
